server:
  port: 8000

web:
  domain: http://localhost

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/baodou?useUnicode=true&characterEncoding=utf8
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    root: info
    com.douyuehan.doubao: debug